### ISSUE TITLE
Issue on the build debug

### ISSUE THREAD

**Issue by willcossak** [szbeni/solar#2]
I can't build "debug" on the project (I attached the screenshot of the issue on the IDE)

Console write :
make: *** [Src/usr/subdir.mk:40: Src/usr/solar.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Src/usr/subdir.mk:40: Src/usr/solar_fan.o] Error 1
../Src/usr/solar_comm.c:1:10: fatal error: main.h: No such file or directory

<img width="1440" alt="Capture d’écran 2022-11-16 à 11 31 36" src="https://user-images.githubusercontent.com/102035884/202157683-61309a24-e51d-46d7-9d6f-d321ffac8b31.png">

**Comment by willcossak** [comment]
<img width="1440" alt="Capture d’écran 2022-11-16 à 11 35 52" src="https://user-images.githubusercontent.com/102035884/202157938-2aafecd5-a8e4-4208-8795-7d969d4dd1fa.png">

**Comment by szbeni** [comment]
I havn't used Cube-IDE for my projects. I usually use vscode or command line with make.
But it looks like you are missing include directory path in your IDE project.
Add an include path pointing to: Inc/usr
Project Properties -> C/C++ Build -> Settings -> Tool Settings -> MCU GCC Compiler -> Include Paths

**Comment by willcossak** [comment]
I'll try with vscode thank you !

**Comment by szbeni** [comment]
updated to STM32Cube_FW_F1 v1.8.4 and added a Cube IDE project file, should  be able to import it and compile.
